### ISSUE TITLE
Can you comment out your ssid and key from the dump or does that invalidate the dump checksums

### ISSUE THREAD

**Issue by Deep-Six** [tuya-cloudcutter/bk7231tools#12]
Hello,
Finally had time to dump the firmware from the Globe 4" downlight, forgot to reset it prior to doing so, thus I can see my ssid and pw in the dump. Can I simply just modify that, or will that invalidate the checksum of the file?

**Comment by kuba2k2** [comment]
You can modify that, as long as you maintain the character count of the SSID and password. But be aware, that your WiFi credentials are also stored in the encrypted data block, by the end of the dump. That is pretty much impossible to modify by hand, and removing that block will make for an incomplete tuya-cloudcutter profile. If you want, you can just create the profile yourself, and make a PR to tuya-cloudcutter.github.io to add that profile.

**Comment by Deep-Six** [comment]
I'll see if I can erase the unit while I still have the pins all soldered up.

**Comment by Deep-Six** [comment]
Its' still there I guess I'll have to do the profile, can you point me to the docs for creating a profile?
Also the tuya-cloudcutter.github.io page doesn't resolve. :(

**Comment by kuba2k2** [comment]
https://github.com/tuya-cloudcutter/tuya-cloudcutter/tree/main/profile-building
