### ISSUE TITLE
Missing PyCryptodome dependency

### ISSUE THREAD

**Issue by narottamroyal** [tuya-cloudcutter/bk7231tools#8]
Just noticed that [storage.py](https://github.com/tuya-cloudcutter/bk7231tools/blob/main/bk7231tools/analysis/storage.py#L11) uses the Cryptodome package, so I believe [pyproject.toml](https://github.com/tuya-cloudcutter/bk7231tools/blob/main/pyproject.toml#L8) should list [pycryptodomex](https://pypi.org/project/pycryptodomex/) as a dependency.

**Comment by Cossid** [comment]
I think most of us testing this have been using a global pip installation.  I have added it as suggested, can you please test/verify?

**Comment by narottamroyal** [comment]
I just tried to build/install in a fresh virtual environment, but `poetry install` failed because `pycryptodomex` is not specified in [poetry.lock](https://github.com/tuya-cloudcutter/bk7231tools/blob/main/poetry.lock)

Running the following command updated the lock file and allowed me to proceed with installation:
```
poetry lock --no-upgrade
```

**Comment by Cossid** [comment]
Ah, I didn't use the tool to add it to the dependency list.  Did this time, and it looks like it was missing file metadata from a prior poetry bug.  Should be fixed now.

**Comment by narottamroyal** [comment]
Yep, all sorted! 😊
