### ISSUE TITLE
'Input file doesn't exit' error

### ISSUE THREAD

**Issue by jf-wm** [tuya-cloudcutter/bk7231tools#9]
System:
Raspberry pi 4
Raspberry pi os 64bit release: September 22nd 2022
bk7231tools 1.1.3
Tuya model CBU - BK7231N

I was able to read the firmware from my tuya model, but i am unable to write new firmware onto it. No matter where i put the firmware bin the tool will always prompt the error 'Input file doesn't exist'

e.g. 
bk7231tools write_flash -d /dev/ttyUSB0 -s 0x11000 -S 0 openbeken7321n.bin
Connected! Chip info: 0x7231c / Flash ID: eb 60 15 / Protocol: FULL
Input file doesn't exist

**Comment by kuba2k2** [comment]
Put the file in the directory where you're running the command.

**Comment by jf-wm** [comment]
I have tried that, it still won't work

**Comment by kuba2k2** [comment]
Post output of ls -las in the same directory as you're running bktools.
